1 nav bar
tcet-opensource/tcet-linux-website pull request #15
Opened 2023-05-14 17:20 UTC by Anshu71

HavBar and Hero Section done....

2023-05-14 19:04 UTC, JayeshVP24 requested changes
Complete the given changes

2023-05-14 19:04 UTC, JayeshVP24 commented on src/components/Hero.astro
> +            <h1 class="2xl:text-7xl xl:text-5xl sm:text-4xl text-3xl mb-2 text-white">Customise your computing experience with TCET Linux
- [x] make 2xl:text-6xl

2023-05-14 19:04 UTC, JayeshVP24 commented on src/components/Hero.astro
> +          <div class=" flex lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
- [ ] remove lg:max-w-lg

basically give 50-50 width to main text div and image div

2023-05-14 19:04 UTC, JayeshVP24 commented on src/components/Hero.astro
> +        <div class="w-11/12 mx-auto flex md:py-16 py-5 md:flex-row flex-col  items-center">
- [x] add little padding bottom

2023-05-14 19:04 UTC, JayeshVP24 commented on src/components/Hero.astro
> +          <div class="absolute z-30 py-0 left-0 w-80 h-96  bg-gradient-to-r from-teal-100 via-indigo-500 to-pink-100 opacity-30 blur-3xl flex-none order-4 rounded-xl transform -rotate-45"></div>
- [x] add `pointer-events-none` in class names

2023-05-14 19:04 UTC, JayeshVP24 commented on src/components/Hero.astro
> +            <div class="hidden md:flex absolute z-30 pt-20 m-14 w-48 h-52 xl:w-[400px] xl:h-[300px] bg-[#98A2B3] opacity-30 blur-2xl flex-none order-4 rounded-full"></div>
- [x] add `pointer-events-none` in  class names

2023-05-14 19:04 UTC, JayeshVP24 commented on src/components/Navbar.jsx
> +                            <div className="ml-4 border-2 border-[#475467] rounded-lg">
- [x] make ml-8

2023-05-14 19:04 UTC, JayeshVP24 commented on src/components/Navbar.jsx
> +                                <button className="inline-flex items-center text-[#E0EAFF] border-1 border-white py-1 px-2 focus:outline-none rounded md:mt-0 hover:underline text-base 2xl:text-lg"><a
- [x] remove underline on hover and rather make a background color gray on hover

2023-05-14 19:04 UTC, JayeshVP24 commented on src/components/Navbar.jsx
> +                            <img src="tcet-opensource-logo.png" alt="" srcSet="" />
- [x] change src to svg logo

2023-05-14 19:04 UTC, JayeshVP24 commented on src/components/Hero.astro
> +          <div class=" flex lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
- [x] remove `w-5/6`

2023-05-14 19:04 UTC, JayeshVP24 commented on src/components/Hero.astro
> +          <div class=" flex lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
change `md:1/2` -> `sm:1/2`

2023-05-14 19:04 UTC, JayeshVP24 commented on src/components/Hero.astro
> +              <button class="inline-flex text-white bg-[#01105F] shadow-base shadow-sky-500 border-sky-500 border-y-2 py-2 px-6 focus:outline-none rounded-3xl text:base md:text-lg">Explore</button>
- [x] add some hover and click effect

2023-05-15 09:12 UTC, riyavishwa981 approved these changes

2023-05-15 11:11 UTC, JayeshVP24 requested changes

2023-05-15 11:11 UTC, JayeshVP24 commented on src/components/Navbar.jsx
> +                            <div className="ml-8 border-2 border-[#475467] rounded-lg">
- [ ] change `ml-8` to important as in `!ml-8`

2023-05-15 11:11 UTC, JayeshVP24 commented on src/components/Hero.astro
> +          <div class=" flex lg:max-w-lg lg:w-full sm:w-1/2">
- [ ] remove `lg:max-w-lg lg:w-full `

2023-05-15 14:51 UTC, JayeshVP24 approved these changes
LGTM

2023-05-15 14:52 UTC, merged